//! Kubernetes Ingress Controller for Phalanx.
//!
//! Watches Kubernetes Ingress and Gateway API resources and translates them
//! into Phalanx RouteConfig entries. Supports:
//! - Ingress v1 (networking.k8s.io/v1)
//! - Gateway API v1 (gateway.networking.k8s.io/v1)
//! - TLS termination with Secret references
//! - Path-based and host-based routing
//! - Annotation-driven configuration overrides

use std::collections::HashMap;
use std::sync::Arc;
use parking_lot::RwLock;
use serde::{Deserialize, Serialize};
use tracing::{debug, info, warn};

/// Represents a Kubernetes Ingress resource (simplified).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IngressResource {
    pub name: String,
    pub namespace: String,
    pub annotations: HashMap<String, String>,
    pub rules: Vec<IngressRule>,
    pub tls: Vec<IngressTls>,
}

/// A single Ingress routing rule.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IngressRule {
    pub host: Option<String>,
    pub paths: Vec<IngressPath>,
}

/// A path entry within an Ingress rule.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IngressPath {
    pub path: String,
    pub path_type: PathType,
    pub backend: IngressBackend,
}

/// Path matching type.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum PathType {
    Exact,
    Prefix,
    ImplementationSpecific,
}

impl PathType {
    pub fn from_str(s: &str) -> Self {
        match s.to_lowercase().as_str() {
            "exact" => Self::Exact,
            "prefix" => Self::Prefix,
            _ => Self::ImplementationSpecific,
        }
    }
}

/// Backend service reference.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IngressBackend {
    pub service_name: String,
    pub service_port: u16,
}

/// TLS configuration from an Ingress resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IngressTls {
    pub hosts: Vec<String>,
    pub secret_name: String,
}

/// Gateway API HTTPRoute resource (simplified).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GatewayHttpRoute {
    pub name: String,
    pub namespace: String,
    pub hostnames: Vec<String>,
    pub rules: Vec<GatewayRule>,
}

/// A Gateway API routing rule.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GatewayRule {
    pub matches: Vec<GatewayMatch>,
    pub backends: Vec<GatewayBackendRef>,
    pub filters: Vec<GatewayFilter>,
}

/// A Gateway API match condition.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GatewayMatch {
    pub path: Option<GatewayPathMatch>,
    pub headers: Vec<GatewayHeaderMatch>,
    pub method: Option<String>,
}

/// Path match for Gateway API.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GatewayPathMatch {
    pub match_type: PathType,
    pub value: String,
}

/// Header match for Gateway API.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GatewayHeaderMatch {
    pub name: String,
    pub value: String,
}

/// Backend reference for Gateway API.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GatewayBackendRef {
    pub service_name: String,
    pub service_port: u16,
    pub weight: u32,
}

/// Gateway API filter (header modification, URL rewrite, etc.).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum GatewayFilter {
    RequestHeaderModifier {
        set: HashMap<String, String>,
        add: HashMap<String, String>,
        remove: Vec<String>,
    },
    URLRewrite {
        path_prefix: Option<String>,
        hostname: Option<String>,
    },
    RequestRedirect {
        scheme: Option<String>,
        hostname: Option<String>,
        port: Option<u16>,
        status_code: u16,
    },
}

/// A route entry generated by the ingress controller.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PhalanxRoute {
    pub path: String,
    pub path_type: PathType,
    pub host: Option<String>,
    pub upstream_pool: String,
    pub backends: Vec<(String, u32)>, // (address:port, weight)
    pub tls_secret: Option<String>,
    pub add_headers: HashMap<String, String>,
    pub rewrite_rules: Vec<(String, String, String)>,
    pub annotations: HashMap<String, String>,
}

/// Annotation keys supported by the Phalanx ingress controller.
pub mod annotations {
    pub const LOAD_BALANCING: &str = "phalanx.io/load-balancing";
    pub const WAF_ENABLED: &str = "phalanx.io/waf-enabled";
    pub const RATE_LIMIT: &str = "phalanx.io/rate-limit";
    pub const SSL_REDIRECT: &str = "phalanx.io/ssl-redirect";
    pub const PROXY_BODY_SIZE: &str = "phalanx.io/proxy-body-size";
    pub const TIMEOUT: &str = "phalanx.io/timeout";
    pub const CORS_ENABLED: &str = "phalanx.io/cors-enabled";
    pub const REWRITE_TARGET: &str = "phalanx.io/rewrite-target";
    pub const CACHE_ENABLED: &str = "phalanx.io/cache-enabled";
    pub const AUTH_TYPE: &str = "phalanx.io/auth-type";
}

/// The Kubernetes Ingress Controller that reconciles K8s resources into Phalanx routes.
pub struct IngressController {
    /// Generated routes from K8s resources
    routes: Arc<RwLock<Vec<PhalanxRoute>>>,
    /// Ingress class name to watch (e.g., "phalanx")
    ingress_class: String,
    /// Cluster DNS suffix for service resolution
    cluster_dns_suffix: String,
}

impl IngressController {
    /// Creates a new ingress controller that watches Ingress resources with
    /// the given class name and resolves services using the cluster DNS suffix.
    pub fn new(ingress_class: &str, cluster_dns_suffix: &str) -> Self {
        Self {
            routes: Arc::new(RwLock::new(Vec::new())),
            ingress_class: ingress_class.to_string(),
            cluster_dns_suffix: cluster_dns_suffix.to_string(),
        }
    }

    /// Resolves a Kubernetes service name to an address using cluster DNS.
    fn resolve_service(&self, namespace: &str, service: &str, port: u16) -> String {
        format!(
            "{}.{}.svc.{}:{}",
            service, namespace, self.cluster_dns_suffix, port
        )
    }

    /// Reconciles an Ingress resource into Phalanx routes.
    pub fn reconcile_ingress(&self, ingress: &IngressResource) -> Vec<PhalanxRoute> {
        let mut routes = Vec::new();

        // Check ingress class annotation
        let class = ingress
            .annotations
            .get("kubernetes.io/ingress.class")
            .map(|s| s.as_str())
            .unwrap_or("phalanx");
        if class != self.ingress_class {
            debug!(
                "Skipping ingress {}/{}: class '{}' != '{}'",
                ingress.namespace, ingress.name, class, self.ingress_class
            );
            return routes;
        }

        // Build TLS host → secret map
        let tls_map: HashMap<String, String> = ingress
            .tls
            .iter()
            .flat_map(|tls| {
                tls.hosts
                    .iter()
                    .map(move |h| (h.clone(), tls.secret_name.clone()))
            })
            .collect();

        for rule in &ingress.rules {
            for path in &rule.paths {
                let upstream_name = format!(
                    "{}-{}-{}",
                    ingress.namespace, path.backend.service_name, path.backend.service_port
                );
                let backend_addr = self.resolve_service(
                    &ingress.namespace,
                    &path.backend.service_name,
                    path.backend.service_port,
                );

                let tls_secret = rule
                    .host
                    .as_ref()
                    .and_then(|h| tls_map.get(h))
                    .cloned();

                // Check for rewrite-target annotation
                let mut rewrite_rules = Vec::new();
                if let Some(target) = ingress.annotations.get(annotations::REWRITE_TARGET) {
                    rewrite_rules.push((
                        format!("^{}(.*)", regex::escape(&path.path)),
                        format!("{}{}", target, "$1"),
                        "break".to_string(),
                    ));
                }

                // Collect add_headers from annotations
                let mut add_headers = HashMap::new();
                if ingress
                    .annotations
                    .get(annotations::CORS_ENABLED)
                    .map(|v| v == "true")
                    .unwrap_or(false)
                {
                    add_headers.insert(
                        "Access-Control-Allow-Origin".to_string(),
                        "*".to_string(),
                    );
                    add_headers.insert(
                        "Access-Control-Allow-Methods".to_string(),
                        "GET, POST, PUT, DELETE, OPTIONS".to_string(),
                    );
                }

                routes.push(PhalanxRoute {
                    path: path.path.clone(),
                    path_type: path.path_type,
                    host: rule.host.clone(),
                    upstream_pool: upstream_name,
                    backends: vec![(backend_addr, 1)],
                    tls_secret,
                    add_headers,
                    rewrite_rules,
                    annotations: ingress.annotations.clone(),
                });
            }
        }

        // Store routes
        let mut stored = self.routes.write();
        stored.retain(|r| {
            !routes
                .iter()
                .any(|nr| nr.path == r.path && nr.host == r.host)
        });
        stored.extend(routes.clone());

        info!(
            "Reconciled ingress {}/{}: {} routes",
            ingress.namespace,
            ingress.name,
            routes.len()
        );

        routes
    }

    /// Reconciles a Gateway API HTTPRoute into Phalanx routes.
    pub fn reconcile_gateway_route(&self, route: &GatewayHttpRoute) -> Vec<PhalanxRoute> {
        let mut phalanx_routes = Vec::new();

        for rule in &route.rules {
            for m in &rule.matches {
                let path = m
                    .path
                    .as_ref()
                    .map(|p| p.value.clone())
                    .unwrap_or_else(|| "/".to_string());
                let path_type = m
                    .path
                    .as_ref()
                    .map(|p| p.match_type)
                    .unwrap_or(PathType::Prefix);

                let backends: Vec<(String, u32)> = rule
                    .backends
                    .iter()
                    .map(|b| {
                        let addr = self.resolve_service(
                            &route.namespace,
                            &b.service_name,
                            b.service_port,
                        );
                        (addr, b.weight)
                    })
                    .collect();

                let upstream_name = format!(
                    "{}-gateway-{}",
                    route.namespace,
                    route
                        .rules
                        .first()
                        .and_then(|r| r.backends.first())
                        .map(|b| b.service_name.as_str())
                        .unwrap_or("default")
                );

                // Process filters
                let mut add_headers = HashMap::new();
                let mut rewrite_rules = Vec::new();
                for filter in &rule.filters {
                    match filter {
                        GatewayFilter::RequestHeaderModifier { set, add, .. } => {
                            add_headers.extend(set.clone());
                            add_headers.extend(add.clone());
                        }
                        GatewayFilter::URLRewrite { path_prefix, .. } => {
                            if let Some(prefix) = path_prefix {
                                rewrite_rules.push((
                                    format!("^{}", regex::escape(&path)),
                                    prefix.clone(),
                                    "break".to_string(),
                                ));
                            }
                        }
                        _ => {}
                    }
                }

                for hostname in &route.hostnames {
                    phalanx_routes.push(PhalanxRoute {
                        path: path.clone(),
                        path_type,
                        host: Some(hostname.clone()),
                        upstream_pool: upstream_name.clone(),
                        backends: backends.clone(),
                        tls_secret: None,
                        add_headers: add_headers.clone(),
                        rewrite_rules: rewrite_rules.clone(),
                        annotations: HashMap::new(),
                    });
                }

                // If no hostnames, add a route without host constraint
                if route.hostnames.is_empty() {
                    phalanx_routes.push(PhalanxRoute {
                        path: path.clone(),
                        path_type,
                        host: None,
                        upstream_pool: upstream_name.clone(),
                        backends: backends.clone(),
                        tls_secret: None,
                        add_headers: add_headers.clone(),
                        rewrite_rules: rewrite_rules.clone(),
                        annotations: HashMap::new(),
                    });
                }
            }
        }

        let mut stored = self.routes.write();
        stored.extend(phalanx_routes.clone());

        info!(
            "Reconciled gateway route {}/{}: {} routes",
            route.namespace,
            route.name,
            phalanx_routes.len()
        );

        phalanx_routes
    }

    /// Removes all routes from a specific ingress resource.
    pub fn remove_ingress(&self, namespace: &str, name: &str) {
        let prefix = format!("{}-", namespace);
        self.routes
            .write()
            .retain(|r| !r.upstream_pool.starts_with(&prefix));
        info!("Removed routes for ingress {}/{}", namespace, name);
    }

    /// Returns all currently active routes.
    pub fn get_routes(&self) -> Vec<PhalanxRoute> {
        self.routes.read().clone()
    }

    /// Returns routes matching a specific host.
    pub fn get_routes_for_host(&self, host: &str) -> Vec<PhalanxRoute> {
        self.routes
            .read()
            .iter()
            .filter(|r| r.host.as_deref() == Some(host) || r.host.is_none())
            .cloned()
            .collect()
    }

    /// Returns the ingress class this controller watches.
    pub fn ingress_class(&self) -> &str {
        &self.ingress_class
    }

    /// Returns the total number of routes.
    pub fn route_count(&self) -> usize {
        self.routes.read().len()
    }

    /// Spawns a Kubernetes watcher that subscribes to Ingress resource changes.
    ///
    /// Connects to the K8s API server (using in-cluster config or kubeconfig),
    /// watches Ingress resources filtered by the configured ingress class, and
    /// calls `reconcile_ingress()` on Added/Modified events.
    ///
    /// Accepts a `CancellationToken` for graceful shutdown.
    pub fn spawn_ingress_watcher(
        self: Arc<Self>,
        cancel: tokio_util::sync::CancellationToken,
    ) {
        tokio::spawn(async move {
            use futures_util::TryStreamExt;

            let client = match kube::Client::try_default().await {
                Ok(c) => c,
                Err(e) => {
                    warn!("K8s Ingress watcher: failed to create client: {}", e);
                    return;
                }
            };

            let ingresses: kube::Api<k8s_openapi::api::networking::v1::Ingress> =
                kube::Api::all(client);
            let watcher_config = kube::runtime::watcher::Config::default();
            let mut stream = std::pin::pin!(
                kube::runtime::watcher(ingresses, watcher_config)
            );

            info!("K8s Ingress watcher started for class '{}'", self.ingress_class);

            loop {
                tokio::select! {
                    event = stream.try_next() => {
                        match event {
                            Ok(Some(kube::runtime::watcher::Event::Apply(ingress))) |
                            Ok(Some(kube::runtime::watcher::Event::InitApply(ingress))) => {
                                if let Some(resource) = k8s_ingress_to_internal(&ingress) {
                                    self.reconcile_ingress(&resource);
                                }
                            }
                            Ok(Some(kube::runtime::watcher::Event::Delete(ingress))) => {
                                let name = ingress.metadata.name.as_deref().unwrap_or("unknown");
                                let ns = ingress.metadata.namespace.as_deref().unwrap_or("default");
                                self.remove_ingress(ns, name);
                            }
                            Ok(Some(kube::runtime::watcher::Event::Init)) |
                            Ok(Some(kube::runtime::watcher::Event::InitDone)) => {}
                            Ok(None) => {
                                info!("K8s Ingress watcher stream ended");
                                break;
                            }
                            Err(e) => {
                                warn!("K8s Ingress watcher error: {}, retrying...", e);
                                tokio::time::sleep(std::time::Duration::from_secs(5)).await;
                            }
                        }
                    }
                    _ = cancel.cancelled() => {
                        info!("K8s Ingress watcher stopping");
                        return;
                    }
                }
            }
        });
    }

    /// Removes all routes generated from a specific Gateway API HTTPRoute resource.
    pub fn remove_gateway_route(&self, namespace: &str, name: &str) {
        let prefix = format!("{}-gateway-", namespace);
        self.routes
            .write()
            .retain(|r| !r.upstream_pool.starts_with(&prefix));
        info!("Removed routes for gateway route {}/{}", namespace, name);
    }

    /// Spawns a Kubernetes watcher that subscribes to Gateway API HTTPRoute
    /// resource changes (gateway.networking.k8s.io/v1).
    ///
    /// On Add/Modify events, calls `reconcile_gateway_route()` to generate
    /// Phalanx routes. On Delete, removes the associated routes.
    ///
    /// Accepts a `CancellationToken` for graceful shutdown.
    pub fn spawn_gateway_watcher(
        self: Arc<Self>,
        cancel: tokio_util::sync::CancellationToken,
    ) {
        tokio::spawn(async move {
            // Gateway API HTTPRoute is a CRD — we use dynamic API access
            let client = match kube::Client::try_default().await {
                Ok(c) => c,
                Err(e) => {
                    warn!("K8s Gateway watcher: failed to create client: {}", e);
                    return;
                }
            };

            // Construct ApiResource for gateway.networking.k8s.io/v1 HTTPRoute
            // This does not require the discovery feature; it builds the resource
            // metadata statically from the well-known Gateway API spec.
            let ar = kube::api::ApiResource {
                group: "gateway.networking.k8s.io".to_string(),
                version: "v1".to_string(),
                kind: "HTTPRoute".to_string(),
                api_version: "gateway.networking.k8s.io/v1".to_string(),
                plural: "httproutes".to_string(),
            };

            let api: kube::Api<kube::api::DynamicObject> =
                kube::Api::all_with(client, &ar);
            let watcher_config = kube::runtime::watcher::Config::default();

            use futures_util::TryStreamExt;
            let mut stream = std::pin::pin!(
                kube::runtime::watcher(api, watcher_config)
            );

            info!("K8s Gateway API watcher started");

            loop {
                tokio::select! {
                    event = stream.try_next() => {
                        match event {
                            Ok(Some(kube::runtime::watcher::Event::Apply(obj))) |
                            Ok(Some(kube::runtime::watcher::Event::InitApply(obj))) => {
                                if let Some(route) = dynamic_to_gateway_route(&obj) {
                                    self.reconcile_gateway_route(&route);
                                }
                            }
                            Ok(Some(kube::runtime::watcher::Event::Delete(obj))) => {
                                let name = obj.metadata.name.as_deref().unwrap_or("unknown");
                                let ns = obj.metadata.namespace.as_deref().unwrap_or("default");
                                self.remove_gateway_route(ns, name);
                            }
                            Ok(Some(kube::runtime::watcher::Event::Init)) |
                            Ok(Some(kube::runtime::watcher::Event::InitDone)) => {}
                            Ok(None) => {
                                info!("K8s Gateway watcher stream ended");
                                break;
                            }
                            Err(e) => {
                                warn!("K8s Gateway watcher error: {}, retrying...", e);
                                tokio::time::sleep(std::time::Duration::from_secs(5)).await;
                            }
                        }
                    }
                    _ = cancel.cancelled() => {
                        info!("K8s Gateway watcher stopping");
                        return;
                    }
                }
            }
        });
    }
}

/// Converts a dynamic K8s object into our internal `GatewayHttpRoute` format.
///
/// Parses the unstructured JSON data from the Gateway API HTTPRoute CRD.
fn dynamic_to_gateway_route(obj: &kube::api::DynamicObject) -> Option<GatewayHttpRoute> {
    let name = obj.metadata.name.clone().unwrap_or_default();
    let namespace = obj
        .metadata
        .namespace
        .clone()
        .unwrap_or_else(|| "default".to_string());

    let spec = obj.data.get("spec")?;

    let hostnames: Vec<String> = spec
        .get("hostnames")
        .and_then(|h| serde_json::from_value(h.clone()).ok())
        .unwrap_or_default();

    let rules: Vec<GatewayRule> = spec
        .get("rules")
        .and_then(|r| r.as_array())
        .map(|rules_arr| {
            rules_arr
                .iter()
                .filter_map(|rule| {
                    let matches = rule
                        .get("matches")
                        .and_then(|m| m.as_array())
                        .map(|matches_arr| {
                            matches_arr
                                .iter()
                                .map(|m| {
                                    let path = m.get("path").map(|p| GatewayPathMatch {
                                        match_type: p
                                            .get("type")
                                            .and_then(|t| t.as_str())
                                            .map(PathType::from_str)
                                            .unwrap_or(PathType::Prefix),
                                        value: p
                                            .get("value")
                                            .and_then(|v| v.as_str())
                                            .unwrap_or("/")
                                            .to_string(),
                                    });
                                    let method = m
                                        .get("method")
                                        .and_then(|v| v.as_str())
                                        .map(String::from);
                                    GatewayMatch {
                                        path,
                                        headers: vec![],
                                        method,
                                    }
                                })
                                .collect()
                        })
                        .unwrap_or_default();

                    let backends = rule
                        .get("backendRefs")
                        .and_then(|b| b.as_array())
                        .map(|arr| {
                            arr.iter()
                                .filter_map(|b| {
                                    Some(GatewayBackendRef {
                                        service_name: b.get("name")?.as_str()?.to_string(),
                                        service_port: b.get("port")?.as_u64()? as u16,
                                        weight: b
                                            .get("weight")
                                            .and_then(|w| w.as_u64())
                                            .unwrap_or(1) as u32,
                                    })
                                })
                                .collect()
                        })
                        .unwrap_or_default();

                    Some(GatewayRule {
                        matches,
                        backends,
                        filters: vec![],
                    })
                })
                .collect()
        })
        .unwrap_or_default();

    Some(GatewayHttpRoute {
        name,
        namespace,
        hostnames,
        rules,
    })
}

/// Converts a native K8s Ingress resource into our internal `IngressResource` format.
fn k8s_ingress_to_internal(
    ingress: &k8s_openapi::api::networking::v1::Ingress,
) -> Option<IngressResource> {
    let metadata = &ingress.metadata;
    let name = metadata.name.clone().unwrap_or_default();
    let namespace = metadata.namespace.clone().unwrap_or_else(|| "default".to_string());
    let annotations: HashMap<String, String> = metadata
        .annotations
        .clone()
        .unwrap_or_default()
        .into_iter()
        .collect();

    let spec = ingress.spec.as_ref()?;

    let rules = spec
        .rules
        .as_ref()
        .map(|rules| {
            rules
                .iter()
                .map(|rule| {
                    let host = rule.host.clone();
                    let paths = rule
                        .http
                        .as_ref()
                        .map(|http| {
                            http.paths
                                .iter()
                                .map(|p| {
                                    let path_type = PathType::from_str(&p.path_type);
                                    IngressPath {
                                        path: p.path.clone().unwrap_or_else(|| "/".to_string()),
                                        path_type,
                                        backend: IngressBackend {
                                            service_name: p
                                                .backend
                                                .service
                                                .as_ref()
                                                .map(|s| s.name.clone())
                                                .unwrap_or_default(),
                                            service_port: p
                                                .backend
                                                .service
                                                .as_ref()
                                                .and_then(|s| s.port.as_ref())
                                                .and_then(|p| p.number)
                                                .unwrap_or(80) as u16,
                                        },
                                    }
                                })
                                .collect()
                        })
                        .unwrap_or_default();
                    IngressRule { host, paths }
                })
                .collect()
        })
        .unwrap_or_default();

    let tls = spec
        .tls
        .as_ref()
        .map(|tls_list| {
            tls_list
                .iter()
                .map(|tls| IngressTls {
                    hosts: tls.hosts.clone().unwrap_or_default(),
                    secret_name: tls.secret_name.clone().unwrap_or_default(),
                })
                .collect()
        })
        .unwrap_or_default();

    Some(IngressResource {
        name,
        namespace,
        annotations,
        rules,
        tls,
    })
}

// ─────────────────────────────────────────────────────────────────────────────
// Unit Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn make_controller() -> IngressController {
        IngressController::new("phalanx", "cluster.local")
    }

    fn make_ingress() -> IngressResource {
        IngressResource {
            name: "my-app".to_string(),
            namespace: "default".to_string(),
            annotations: {
                let mut a = HashMap::new();
                a.insert("kubernetes.io/ingress.class".to_string(), "phalanx".to_string());
                a
            },
            rules: vec![IngressRule {
                host: Some("app.example.com".to_string()),
                paths: vec![IngressPath {
                    path: "/api".to_string(),
                    path_type: PathType::Prefix,
                    backend: IngressBackend {
                        service_name: "api-svc".to_string(),
                        service_port: 8080,
                    },
                }],
            }],
            tls: vec![IngressTls {
                hosts: vec!["app.example.com".to_string()],
                secret_name: "app-tls".to_string(),
            }],
        }
    }

    #[test]
    fn test_controller_creation() {
        let ctrl = make_controller();
        assert_eq!(ctrl.ingress_class(), "phalanx");
        assert_eq!(ctrl.route_count(), 0);
    }

    #[test]
    fn test_reconcile_ingress_basic() {
        let ctrl = make_controller();
        let ingress = make_ingress();
        let routes = ctrl.reconcile_ingress(&ingress);
        assert_eq!(routes.len(), 1);
        assert_eq!(routes[0].path, "/api");
        assert_eq!(routes[0].host, Some("app.example.com".to_string()));
        assert!(routes[0].backends[0].0.contains("api-svc"));
        assert_eq!(routes[0].tls_secret, Some("app-tls".to_string()));
    }

    #[test]
    fn test_reconcile_ingress_wrong_class() {
        let ctrl = make_controller();
        let mut ingress = make_ingress();
        ingress.annotations.insert(
            "kubernetes.io/ingress.class".to_string(),
            "nginx".to_string(),
        );
        let routes = ctrl.reconcile_ingress(&ingress);
        assert_eq!(routes.len(), 0);
    }

    #[test]
    fn test_reconcile_ingress_with_rewrite() {
        let ctrl = make_controller();
        let mut ingress = make_ingress();
        ingress.annotations.insert(
            annotations::REWRITE_TARGET.to_string(),
            "/v2".to_string(),
        );
        let routes = ctrl.reconcile_ingress(&ingress);
        assert_eq!(routes[0].rewrite_rules.len(), 1);
        assert!(routes[0].rewrite_rules[0].1.contains("/v2"));
    }

    #[test]
    fn test_reconcile_ingress_with_cors() {
        let ctrl = make_controller();
        let mut ingress = make_ingress();
        ingress.annotations.insert(
            annotations::CORS_ENABLED.to_string(),
            "true".to_string(),
        );
        let routes = ctrl.reconcile_ingress(&ingress);
        assert!(routes[0].add_headers.contains_key("Access-Control-Allow-Origin"));
    }

    #[test]
    fn test_reconcile_multiple_paths() {
        let ctrl = make_controller();
        let ingress = IngressResource {
            name: "multi".to_string(),
            namespace: "default".to_string(),
            annotations: {
                let mut a = HashMap::new();
                a.insert("kubernetes.io/ingress.class".to_string(), "phalanx".to_string());
                a
            },
            rules: vec![IngressRule {
                host: Some("example.com".to_string()),
                paths: vec![
                    IngressPath {
                        path: "/api".to_string(),
                        path_type: PathType::Prefix,
                        backend: IngressBackend {
                            service_name: "api-svc".to_string(),
                            service_port: 8080,
                        },
                    },
                    IngressPath {
                        path: "/web".to_string(),
                        path_type: PathType::Prefix,
                        backend: IngressBackend {
                            service_name: "web-svc".to_string(),
                            service_port: 3000,
                        },
                    },
                ],
            }],
            tls: vec![],
        };
        let routes = ctrl.reconcile_ingress(&ingress);
        assert_eq!(routes.len(), 2);
    }

    #[test]
    fn test_resolve_service_address() {
        let ctrl = make_controller();
        let addr = ctrl.resolve_service("default", "my-svc", 8080);
        assert_eq!(addr, "my-svc.default.svc.cluster.local:8080");
    }

    #[test]
    fn test_get_routes_for_host() {
        let ctrl = make_controller();
        let ingress = make_ingress();
        ctrl.reconcile_ingress(&ingress);
        let routes = ctrl.get_routes_for_host("app.example.com");
        assert_eq!(routes.len(), 1);
        let no_routes = ctrl.get_routes_for_host("other.example.com");
        assert_eq!(no_routes.len(), 0);
    }

    #[test]
    fn test_remove_ingress() {
        let ctrl = make_controller();
        let ingress = make_ingress();
        ctrl.reconcile_ingress(&ingress);
        assert_eq!(ctrl.route_count(), 1);
        ctrl.remove_ingress("default", "my-app");
        assert_eq!(ctrl.route_count(), 0);
    }

    #[test]
    fn test_path_type_from_str() {
        assert_eq!(PathType::from_str("exact"), PathType::Exact);
        assert_eq!(PathType::from_str("prefix"), PathType::Prefix);
        assert_eq!(PathType::from_str("Prefix"), PathType::Prefix);
        assert_eq!(PathType::from_str("other"), PathType::ImplementationSpecific);
    }

    #[test]
    fn test_ingress_resource_serialization() {
        let ingress = make_ingress();
        let json = serde_json::to_string(&ingress).unwrap();
        let decoded: IngressResource = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.name, "my-app");
        assert_eq!(decoded.rules.len(), 1);
    }

    #[test]
    fn test_reconcile_gateway_route() {
        let ctrl = make_controller();
        let route = GatewayHttpRoute {
            name: "api-route".to_string(),
            namespace: "default".to_string(),
            hostnames: vec!["api.example.com".to_string()],
            rules: vec![GatewayRule {
                matches: vec![GatewayMatch {
                    path: Some(GatewayPathMatch {
                        match_type: PathType::Prefix,
                        value: "/v1".to_string(),
                    }),
                    headers: vec![],
                    method: None,
                }],
                backends: vec![GatewayBackendRef {
                    service_name: "api-v1".to_string(),
                    service_port: 8080,
                    weight: 1,
                }],
                filters: vec![],
            }],
        };
        let routes = ctrl.reconcile_gateway_route(&route);
        assert_eq!(routes.len(), 1);
        assert_eq!(routes[0].path, "/v1");
        assert_eq!(routes[0].host, Some("api.example.com".to_string()));
    }

    #[test]
    fn test_gateway_route_with_header_filter() {
        let ctrl = make_controller();
        let route = GatewayHttpRoute {
            name: "filtered".to_string(),
            namespace: "prod".to_string(),
            hostnames: vec!["app.test.com".to_string()],
            rules: vec![GatewayRule {
                matches: vec![GatewayMatch {
                    path: Some(GatewayPathMatch {
                        match_type: PathType::Prefix,
                        value: "/".to_string(),
                    }),
                    headers: vec![],
                    method: None,
                }],
                backends: vec![GatewayBackendRef {
                    service_name: "app-svc".to_string(),
                    service_port: 80,
                    weight: 1,
                }],
                filters: vec![GatewayFilter::RequestHeaderModifier {
                    set: {
                        let mut m = HashMap::new();
                        m.insert("X-Env".to_string(), "prod".to_string());
                        m
                    },
                    add: HashMap::new(),
                    remove: vec![],
                }],
            }],
        };
        let routes = ctrl.reconcile_gateway_route(&route);
        assert_eq!(routes[0].add_headers.get("X-Env"), Some(&"prod".to_string()));
    }

    #[test]
    fn test_gateway_route_no_hostnames() {
        let ctrl = make_controller();
        let route = GatewayHttpRoute {
            name: "catchall".to_string(),
            namespace: "default".to_string(),
            hostnames: vec![],
            rules: vec![GatewayRule {
                matches: vec![GatewayMatch {
                    path: Some(GatewayPathMatch {
                        match_type: PathType::Prefix,
                        value: "/".to_string(),
                    }),
                    headers: vec![],
                    method: None,
                }],
                backends: vec![GatewayBackendRef {
                    service_name: "default-svc".to_string(),
                    service_port: 80,
                    weight: 1,
                }],
                filters: vec![],
            }],
        };
        let routes = ctrl.reconcile_gateway_route(&route);
        assert_eq!(routes.len(), 1);
        assert!(routes[0].host.is_none());
    }

    #[test]
    fn test_gateway_route_weighted_backends() {
        let ctrl = make_controller();
        let route = GatewayHttpRoute {
            name: "canary".to_string(),
            namespace: "default".to_string(),
            hostnames: vec!["canary.example.com".to_string()],
            rules: vec![GatewayRule {
                matches: vec![GatewayMatch {
                    path: Some(GatewayPathMatch {
                        match_type: PathType::Prefix,
                        value: "/".to_string(),
                    }),
                    headers: vec![],
                    method: None,
                }],
                backends: vec![
                    GatewayBackendRef { service_name: "stable".to_string(), service_port: 80, weight: 90 },
                    GatewayBackendRef { service_name: "canary".to_string(), service_port: 80, weight: 10 },
                ],
                filters: vec![],
            }],
        };
        let routes = ctrl.reconcile_gateway_route(&route);
        assert_eq!(routes[0].backends.len(), 2);
        assert_eq!(routes[0].backends[0].1, 90);
        assert_eq!(routes[0].backends[1].1, 10);
    }

    #[test]
    fn test_gateway_filter_serialization() {
        let filter = GatewayFilter::RequestRedirect {
            scheme: Some("https".to_string()),
            hostname: None,
            port: Some(443),
            status_code: 301,
        };
        let json = serde_json::to_string(&filter).unwrap();
        assert!(json.contains("301"));
    }

    #[test]
    fn test_annotations_constants() {
        assert_eq!(annotations::LOAD_BALANCING, "phalanx.io/load-balancing");
        assert_eq!(annotations::WAF_ENABLED, "phalanx.io/waf-enabled");
        assert_eq!(annotations::SSL_REDIRECT, "phalanx.io/ssl-redirect");
    }

    #[test]
    fn test_k8s_ingress_to_internal_basic() {
        use k8s_openapi::api::networking::v1 as netv1;

        let ingress = netv1::Ingress {
            metadata: kube::api::ObjectMeta {
                name: Some("my-ingress".to_string()),
                namespace: Some("default".to_string()),
                annotations: Some({
                    let mut a = std::collections::BTreeMap::new();
                    a.insert("kubernetes.io/ingress.class".to_string(), "phalanx".to_string());
                    a
                }),
                ..Default::default()
            },
            spec: Some(netv1::IngressSpec {
                rules: Some(vec![netv1::IngressRule {
                    host: Some("example.com".to_string()),
                    http: Some(netv1::HTTPIngressRuleValue {
                        paths: vec![netv1::HTTPIngressPath {
                            path: Some("/api".to_string()),
                            path_type: "Prefix".to_string(),
                            backend: netv1::IngressBackend {
                                service: Some(netv1::IngressServiceBackend {
                                    name: "api-svc".to_string(),
                                    port: Some(netv1::ServiceBackendPort {
                                        number: Some(8080),
                                        ..Default::default()
                                    }),
                                }),
                                ..Default::default()
                            },
                        }],
                    }),
                }]),
                tls: Some(vec![netv1::IngressTLS {
                    hosts: Some(vec!["example.com".to_string()]),
                    secret_name: Some("tls-secret".to_string()),
                }]),
                ..Default::default()
            }),
            ..Default::default()
        };

        let result = k8s_ingress_to_internal(&ingress);
        assert!(result.is_some());
        let resource = result.unwrap();
        assert_eq!(resource.name, "my-ingress");
        assert_eq!(resource.namespace, "default");
        assert_eq!(resource.rules.len(), 1);
        assert_eq!(resource.rules[0].paths[0].path, "/api");
        assert_eq!(resource.rules[0].paths[0].backend.service_name, "api-svc");
        assert_eq!(resource.rules[0].paths[0].backend.service_port, 8080);
        assert_eq!(resource.tls.len(), 1);
        assert_eq!(resource.tls[0].secret_name, "tls-secret");
    }

    #[test]
    fn test_k8s_ingress_to_internal_no_spec() {
        use k8s_openapi::api::networking::v1 as netv1;
        let ingress = netv1::Ingress {
            metadata: kube::api::ObjectMeta::default(),
            spec: None,
            ..Default::default()
        };
        assert!(k8s_ingress_to_internal(&ingress).is_none());
    }

    #[test]
    fn test_phalanx_route_serialization() {
        let route = PhalanxRoute {
            path: "/test".to_string(),
            path_type: PathType::Prefix,
            host: Some("test.com".to_string()),
            upstream_pool: "test-pool".to_string(),
            backends: vec![("10.0.0.1:80".to_string(), 1)],
            tls_secret: None,
            add_headers: HashMap::new(),
            rewrite_rules: vec![],
            annotations: HashMap::new(),
        };
        let json = serde_json::to_string(&route).unwrap();
        let decoded: PhalanxRoute = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.path, "/test");
    }

    #[test]
    fn test_remove_gateway_route() {
        let ctrl = make_controller();
        let route = GatewayHttpRoute {
            name: "api-route".to_string(),
            namespace: "default".to_string(),
            hostnames: vec!["api.example.com".to_string()],
            rules: vec![GatewayRule {
                matches: vec![GatewayMatch {
                    path: Some(GatewayPathMatch {
                        match_type: PathType::Prefix,
                        value: "/v1".to_string(),
                    }),
                    headers: vec![],
                    method: None,
                }],
                backends: vec![GatewayBackendRef {
                    service_name: "api-v1".to_string(),
                    service_port: 8080,
                    weight: 1,
                }],
                filters: vec![],
            }],
        };
        ctrl.reconcile_gateway_route(&route);
        assert!(ctrl.route_count() > 0);
        ctrl.remove_gateway_route("default", "api-route");
        assert_eq!(ctrl.route_count(), 0);
    }

    #[test]
    fn test_dynamic_to_gateway_route_basic() {
        let mut data = serde_json::Map::new();
        let spec = serde_json::json!({
            "hostnames": ["test.example.com"],
            "rules": [{
                "matches": [{
                    "path": {
                        "type": "Prefix",
                        "value": "/api"
                    }
                }],
                "backendRefs": [{
                    "name": "api-svc",
                    "port": 8080,
                    "weight": 1
                }]
            }]
        });
        data.insert("spec".to_string(), spec);

        let obj = kube::api::DynamicObject {
            metadata: kube::api::ObjectMeta {
                name: Some("test-route".to_string()),
                namespace: Some("default".to_string()),
                ..Default::default()
            },
            types: None,
            data: serde_json::Value::Object(data),
        };

        let route = dynamic_to_gateway_route(&obj);
        assert!(route.is_some());
        let route = route.unwrap();
        assert_eq!(route.name, "test-route");
        assert_eq!(route.namespace, "default");
        assert_eq!(route.hostnames, vec!["test.example.com"]);
        assert_eq!(route.rules.len(), 1);
        assert_eq!(route.rules[0].backends.len(), 1);
        assert_eq!(route.rules[0].backends[0].service_name, "api-svc");
        assert_eq!(route.rules[0].backends[0].service_port, 8080);
    }

    #[test]
    fn test_dynamic_to_gateway_route_no_spec() {
        let obj = kube::api::DynamicObject {
            metadata: kube::api::ObjectMeta::default(),
            types: None,
            data: serde_json::Value::Object(serde_json::Map::new()),
        };
        assert!(dynamic_to_gateway_route(&obj).is_none());
    }
}
