//! Proxy-Wasm plugin extensibility framework.
//!
//! Provides a WebAssembly-based plugin system for extending Phalanx with custom
//! request/response processing logic. Plugins can be written in Rust, Go, or C++
//! and compiled to `.wasm` files.
//!
//! This module implements the proxy-wasm ABI v0.2.1 host side, allowing plugins
//! to intercept requests at multiple phases: OnRequestHeaders, OnRequestBody,
//! OnResponseHeaders, OnResponseBody, and OnLog.

use std::collections::HashMap;
use std::path::Path;
use std::sync::Arc;
use parking_lot::RwLock;
use serde::{Deserialize, Serialize};
use tracing::{debug, error, info, warn};

/// Proxy-Wasm ABI action returned by plugin callbacks.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum WasmAction {
    /// Continue processing the request/response normally.
    Continue,
    /// Pause processing (e.g., waiting for an async call).
    Pause,
}

/// Phase in the request lifecycle where a Wasm plugin can intervene.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum WasmPhase {
    OnRequestHeaders,
    OnRequestBody,
    OnResponseHeaders,
    OnResponseBody,
    OnLog,
    OnTick,
}

/// Header pair used in the Wasm ABI.
pub type HeaderMap = Vec<(String, String)>;

/// Context passed to Wasm plugins during request processing.
#[derive(Debug, Clone)]
pub struct WasmRequestContext {
    pub method: String,
    pub path: String,
    pub query: Option<String>,
    pub headers: HeaderMap,
    pub body: Option<Vec<u8>>,
    pub client_ip: String,
    pub protocol: String,
}

/// Context for response processing.
#[derive(Debug, Clone)]
pub struct WasmResponseContext {
    pub status_code: u16,
    pub headers: HeaderMap,
    pub body: Option<Vec<u8>>,
}

/// Result of a plugin invocation.
#[derive(Debug, Clone)]
pub struct WasmPluginResult {
    pub action: WasmAction,
    /// Modified headers (if any)
    pub headers: Option<HeaderMap>,
    /// Modified body (if any)
    pub body: Option<Vec<u8>>,
    /// Direct response to send (short-circuit)
    pub direct_response: Option<WasmDirectResponse>,
    /// Metadata set by the plugin
    pub metadata: HashMap<String, String>,
}

impl Default for WasmPluginResult {
    fn default() -> Self {
        Self {
            action: WasmAction::Continue,
            headers: None,
            body: None,
            direct_response: None,
            metadata: HashMap::new(),
        }
    }
}

/// A direct HTTP response generated by a plugin (short-circuit).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WasmDirectResponse {
    pub status_code: u16,
    pub headers: HeaderMap,
    pub body: Vec<u8>,
}

/// Configuration for a loaded Wasm plugin.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WasmPluginConfig {
    /// Unique name for this plugin instance
    pub name: String,
    /// Path to the .wasm file
    pub wasm_path: String,
    /// Plugin configuration string (JSON/YAML passed to the plugin)
    pub config: String,
    /// Phases this plugin should run in
    pub phases: Vec<WasmPhase>,
    /// Priority (lower = runs first). Default: 100.
    pub priority: u32,
    /// Whether this plugin is enabled
    pub enabled: bool,
}

impl Default for WasmPluginConfig {
    fn default() -> Self {
        Self {
            name: String::new(),
            wasm_path: String::new(),
            config: String::new(),
            phases: vec![WasmPhase::OnRequestHeaders],
            priority: 100,
            enabled: true,
        }
    }
}

/// Trait that all Wasm plugin implementations must satisfy.
/// This abstracts over the actual Wasm runtime (wasmtime, wasmer, etc.)
/// and allows for native Rust plugins as well.
pub trait WasmPlugin: Send + Sync {
    /// Returns the plugin name.
    fn name(&self) -> &str;

    /// Called when request headers are received.
    fn on_request_headers(&self, ctx: &WasmRequestContext) -> WasmPluginResult {
        let _ = ctx;
        WasmPluginResult::default()
    }

    /// Called when the request body is received.
    fn on_request_body(&self, ctx: &WasmRequestContext) -> WasmPluginResult {
        let _ = ctx;
        WasmPluginResult::default()
    }

    /// Called when response headers are received.
    fn on_response_headers(&self, ctx: &WasmResponseContext) -> WasmPluginResult {
        let _ = ctx;
        WasmPluginResult::default()
    }

    /// Called when the response body is received.
    fn on_response_body(&self, ctx: &WasmResponseContext) -> WasmPluginResult {
        let _ = ctx;
        WasmPluginResult::default()
    }

    /// Called at the end of request processing (for logging/metrics).
    fn on_log(&self, req: &WasmRequestContext, resp: &WasmResponseContext) -> WasmPluginResult {
        let _ = (req, resp);
        WasmPluginResult::default()
    }
}

/// A native Rust plugin that adds custom headers to requests.
pub struct HeaderInjectionPlugin {
    name: String,
    headers_to_add: Vec<(String, String)>,
}

impl HeaderInjectionPlugin {
    pub fn new(name: &str, headers: Vec<(String, String)>) -> Self {
        Self {
            name: name.to_string(),
            headers_to_add: headers,
        }
    }
}

impl WasmPlugin for HeaderInjectionPlugin {
    fn name(&self) -> &str {
        &self.name
    }

    fn on_request_headers(&self, _ctx: &WasmRequestContext) -> WasmPluginResult {
        WasmPluginResult {
            action: WasmAction::Continue,
            headers: Some(self.headers_to_add.clone()),
            ..Default::default()
        }
    }
}

/// A native Rust plugin that rate-limits based on a header value.
pub struct HeaderRateLimitPlugin {
    name: String,
    header_name: String,
    max_requests: u64,
    counters: Arc<RwLock<HashMap<String, u64>>>,
}

impl HeaderRateLimitPlugin {
    pub fn new(name: &str, header_name: &str, max_requests: u64) -> Self {
        Self {
            name: name.to_string(),
            header_name: header_name.to_string(),
            max_requests,
            counters: Arc::new(RwLock::new(HashMap::new())),
        }
    }
}

impl WasmPlugin for HeaderRateLimitPlugin {
    fn name(&self) -> &str {
        &self.name
    }

    fn on_request_headers(&self, ctx: &WasmRequestContext) -> WasmPluginResult {
        let key = ctx
            .headers
            .iter()
            .find(|(k, _)| k.eq_ignore_ascii_case(&self.header_name))
            .map(|(_, v)| v.clone())
            .unwrap_or_else(|| ctx.client_ip.clone());

        let mut counters = self.counters.write();
        let count = counters.entry(key).or_insert(0);
        *count += 1;

        if *count > self.max_requests {
            WasmPluginResult {
                action: WasmAction::Continue,
                direct_response: Some(WasmDirectResponse {
                    status_code: 429,
                    headers: vec![("Retry-After".to_string(), "60".to_string())],
                    body: b"Rate limit exceeded".to_vec(),
                }),
                ..Default::default()
            }
        } else {
            WasmPluginResult::default()
        }
    }
}

/// A native Rust plugin that blocks requests matching path patterns.
pub struct PathBlockerPlugin {
    name: String,
    blocked_patterns: Vec<String>,
}

impl PathBlockerPlugin {
    pub fn new(name: &str, patterns: Vec<String>) -> Self {
        Self {
            name: name.to_string(),
            blocked_patterns: patterns,
        }
    }
}

impl WasmPlugin for PathBlockerPlugin {
    fn name(&self) -> &str {
        &self.name
    }

    fn on_request_headers(&self, ctx: &WasmRequestContext) -> WasmPluginResult {
        for pattern in &self.blocked_patterns {
            if ctx.path.contains(pattern) {
                return WasmPluginResult {
                    action: WasmAction::Continue,
                    direct_response: Some(WasmDirectResponse {
                        status_code: 403,
                        headers: vec![("Content-Type".to_string(), "text/plain".to_string())],
                        body: format!("Blocked by policy: path matches '{}'", pattern).into_bytes(),
                    }),
                    ..Default::default()
                };
            }
        }
        WasmPluginResult::default()
    }
}

/// The plugin manager that orchestrates all registered Wasm plugins.
pub struct WasmPluginManager {
    /// Registered plugins, sorted by priority
    plugins: Arc<RwLock<Vec<PluginEntry>>>,
}

struct PluginEntry {
    plugin: Arc<dyn WasmPlugin>,
    config: WasmPluginConfig,
}

impl WasmPluginManager {
    pub fn new() -> Self {
        Self {
            plugins: Arc::new(RwLock::new(Vec::new())),
        }
    }

    /// Registers a plugin with the given configuration.
    pub fn register(&self, plugin: Arc<dyn WasmPlugin>, config: WasmPluginConfig) {
        let mut plugins = self.plugins.write();
        info!("Wasm plugin registered: {} (priority: {})", config.name, config.priority);
        plugins.push(PluginEntry { plugin, config });
        plugins.sort_by_key(|e| e.config.priority);
    }

    /// Removes a plugin by name.
    pub fn unregister(&self, name: &str) -> bool {
        let mut plugins = self.plugins.write();
        let before = plugins.len();
        plugins.retain(|e| e.config.name != name);
        let removed = plugins.len() < before;
        if removed {
            info!("Wasm plugin unregistered: {}", name);
        }
        removed
    }

    /// Returns the number of registered plugins.
    pub fn plugin_count(&self) -> usize {
        self.plugins.read().len()
    }

    /// Lists all registered plugin names.
    pub fn plugin_names(&self) -> Vec<String> {
        self.plugins.read().iter().map(|e| e.config.name.clone()).collect()
    }

    /// Executes all plugins for the OnRequestHeaders phase.
    pub fn execute_request_headers(&self, ctx: &WasmRequestContext) -> WasmPluginResult {
        let plugins = self.plugins.read();
        let mut merged = WasmPluginResult::default();

        for entry in plugins.iter() {
            if !entry.config.enabled || !entry.config.phases.contains(&WasmPhase::OnRequestHeaders) {
                continue;
            }
            let result = entry.plugin.on_request_headers(ctx);

            // If a plugin sends a direct response, short-circuit
            if result.direct_response.is_some() {
                return result;
            }

            // Merge headers
            if let Some(hdrs) = result.headers {
                merged
                    .headers
                    .get_or_insert_with(Vec::new)
                    .extend(hdrs);
            }

            // Merge metadata
            merged.metadata.extend(result.metadata);

            if result.action == WasmAction::Pause {
                merged.action = WasmAction::Pause;
            }
        }

        merged
    }

    /// Executes all plugins for the OnRequestBody phase.
    pub fn execute_request_body(&self, ctx: &WasmRequestContext) -> WasmPluginResult {
        let plugins = self.plugins.read();
        let mut merged = WasmPluginResult::default();

        for entry in plugins.iter() {
            if !entry.config.enabled || !entry.config.phases.contains(&WasmPhase::OnRequestBody) {
                continue;
            }
            let result = entry.plugin.on_request_body(ctx);
            if result.direct_response.is_some() {
                return result;
            }
            if let Some(body) = result.body {
                merged.body = Some(body);
            }
            merged.metadata.extend(result.metadata);
        }

        merged
    }

    /// Executes all plugins for the OnResponseHeaders phase.
    pub fn execute_response_headers(&self, ctx: &WasmResponseContext) -> WasmPluginResult {
        let plugins = self.plugins.read();
        let mut merged = WasmPluginResult::default();

        for entry in plugins.iter() {
            if !entry.config.enabled || !entry.config.phases.contains(&WasmPhase::OnResponseHeaders)
            {
                continue;
            }
            let result = entry.plugin.on_response_headers(ctx);
            if let Some(hdrs) = result.headers {
                merged.headers.get_or_insert_with(Vec::new).extend(hdrs);
            }
            merged.metadata.extend(result.metadata);
        }

        merged
    }

    /// Executes all plugins for the OnResponseBody phase.
    pub fn execute_response_body(&self, ctx: &WasmResponseContext) -> WasmPluginResult {
        let plugins = self.plugins.read();
        let mut merged = WasmPluginResult::default();

        for entry in plugins.iter() {
            if !entry.config.enabled || !entry.config.phases.contains(&WasmPhase::OnResponseBody) {
                continue;
            }
            let result = entry.plugin.on_response_body(ctx);
            if let Some(body) = result.body {
                merged.body = Some(body);
            }
            merged.metadata.extend(result.metadata);
        }

        merged
    }

    /// Executes all plugins for the OnLog phase.
    pub fn execute_log(
        &self,
        req_ctx: &WasmRequestContext,
        resp_ctx: &WasmResponseContext,
    ) -> WasmPluginResult {
        let plugins = self.plugins.read();
        let mut merged = WasmPluginResult::default();

        for entry in plugins.iter() {
            if !entry.config.enabled || !entry.config.phases.contains(&WasmPhase::OnLog) {
                continue;
            }
            let result = entry.plugin.on_log(req_ctx, resp_ctx);
            merged.metadata.extend(result.metadata);
        }

        merged
    }

    /// Loads a plugin configuration from a JSON file.
    pub fn load_config_from_file(path: &str) -> Result<Vec<WasmPluginConfig>, String> {
        let content =
            std::fs::read_to_string(path).map_err(|e| format!("read error: {}", e))?;
        serde_json::from_str(&content).map_err(|e| format!("parse error: {}", e))
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Unit Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn make_request_ctx() -> WasmRequestContext {
        WasmRequestContext {
            method: "GET".to_string(),
            path: "/api/users".to_string(),
            query: Some("page=1".to_string()),
            headers: vec![
                ("Host".to_string(), "example.com".to_string()),
                ("User-Agent".to_string(), "TestClient/1.0".to_string()),
            ],
            body: None,
            client_ip: "10.0.0.1".to_string(),
            protocol: "HTTP/1.1".to_string(),
        }
    }

    fn make_response_ctx() -> WasmResponseContext {
        WasmResponseContext {
            status_code: 200,
            headers: vec![("Content-Type".to_string(), "application/json".to_string())],
            body: Some(b"{}".to_vec()),
        }
    }

    // ── WasmAction Tests ────────────────────────────────────────────────────

    #[test]
    fn test_wasm_action_equality() {
        assert_eq!(WasmAction::Continue, WasmAction::Continue);
        assert_eq!(WasmAction::Pause, WasmAction::Pause);
        assert_ne!(WasmAction::Continue, WasmAction::Pause);
    }

    #[test]
    fn test_wasm_action_serialization() {
        let json = serde_json::to_string(&WasmAction::Continue).unwrap();
        let decoded: WasmAction = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded, WasmAction::Continue);
    }

    // ── WasmPhase Tests ─────────────────────────────────────────────────────

    #[test]
    fn test_wasm_phase_equality() {
        assert_eq!(WasmPhase::OnRequestHeaders, WasmPhase::OnRequestHeaders);
        assert_ne!(WasmPhase::OnRequestHeaders, WasmPhase::OnResponseBody);
    }

    #[test]
    fn test_wasm_phase_serialization() {
        let json = serde_json::to_string(&WasmPhase::OnLog).unwrap();
        let decoded: WasmPhase = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded, WasmPhase::OnLog);
    }

    // ── WasmPluginConfig Tests ──────────────────────────────────────────────

    #[test]
    fn test_plugin_config_default() {
        let cfg = WasmPluginConfig::default();
        assert!(cfg.name.is_empty());
        assert_eq!(cfg.priority, 100);
        assert!(cfg.enabled);
        assert_eq!(cfg.phases, vec![WasmPhase::OnRequestHeaders]);
    }

    #[test]
    fn test_plugin_config_serialization() {
        let cfg = WasmPluginConfig {
            name: "test-plugin".to_string(),
            wasm_path: "/path/to/plugin.wasm".to_string(),
            config: r#"{"key":"value"}"#.to_string(),
            phases: vec![WasmPhase::OnRequestHeaders, WasmPhase::OnLog],
            priority: 50,
            enabled: true,
        };
        let json = serde_json::to_string(&cfg).unwrap();
        let decoded: WasmPluginConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.name, "test-plugin");
        assert_eq!(decoded.priority, 50);
        assert_eq!(decoded.phases.len(), 2);
    }

    // ── WasmPluginResult Tests ──────────────────────────────────────────────

    #[test]
    fn test_plugin_result_default() {
        let result = WasmPluginResult::default();
        assert_eq!(result.action, WasmAction::Continue);
        assert!(result.headers.is_none());
        assert!(result.body.is_none());
        assert!(result.direct_response.is_none());
        assert!(result.metadata.is_empty());
    }

    // ── HeaderInjectionPlugin Tests ─────────────────────────────────────────

    #[test]
    fn test_header_injection_plugin_name() {
        let plugin = HeaderInjectionPlugin::new("injector", vec![]);
        assert_eq!(plugin.name(), "injector");
    }

    #[test]
    fn test_header_injection_adds_headers() {
        let plugin = HeaderInjectionPlugin::new(
            "injector",
            vec![
                ("X-Custom".to_string(), "value1".to_string()),
                ("X-Trace-Id".to_string(), "abc123".to_string()),
            ],
        );
        let ctx = make_request_ctx();
        let result = plugin.on_request_headers(&ctx);
        assert_eq!(result.action, WasmAction::Continue);
        let headers = result.headers.unwrap();
        assert_eq!(headers.len(), 2);
        assert_eq!(headers[0].0, "X-Custom");
        assert_eq!(headers[1].1, "abc123");
    }

    #[test]
    fn test_header_injection_empty_headers() {
        let plugin = HeaderInjectionPlugin::new("empty", vec![]);
        let ctx = make_request_ctx();
        let result = plugin.on_request_headers(&ctx);
        assert!(result.headers.unwrap().is_empty());
    }

    // ── HeaderRateLimitPlugin Tests ─────────────────────────────────────────

    #[test]
    fn test_header_rate_limit_allows_under_limit() {
        let plugin = HeaderRateLimitPlugin::new("rl", "X-API-Key", 10);
        let mut ctx = make_request_ctx();
        ctx.headers.push(("X-API-Key".to_string(), "key-1".to_string()));
        for _ in 0..10 {
            let result = plugin.on_request_headers(&ctx);
            assert!(result.direct_response.is_none());
        }
    }

    #[test]
    fn test_header_rate_limit_blocks_over_limit() {
        let plugin = HeaderRateLimitPlugin::new("rl", "X-API-Key", 5);
        let mut ctx = make_request_ctx();
        ctx.headers.push(("X-API-Key".to_string(), "key-2".to_string()));
        for _ in 0..5 {
            plugin.on_request_headers(&ctx);
        }
        let result = plugin.on_request_headers(&ctx);
        assert!(result.direct_response.is_some());
        assert_eq!(result.direct_response.unwrap().status_code, 429);
    }

    #[test]
    fn test_header_rate_limit_uses_ip_when_no_header() {
        let plugin = HeaderRateLimitPlugin::new("rl", "X-Missing", 3);
        let ctx = make_request_ctx();
        for _ in 0..3 {
            plugin.on_request_headers(&ctx);
        }
        let result = plugin.on_request_headers(&ctx);
        assert!(result.direct_response.is_some());
    }

    #[test]
    fn test_header_rate_limit_separate_keys() {
        let plugin = HeaderRateLimitPlugin::new("rl", "X-API-Key", 2);
        let mut ctx1 = make_request_ctx();
        ctx1.headers.push(("X-API-Key".to_string(), "a".to_string()));
        let mut ctx2 = make_request_ctx();
        ctx2.headers.push(("X-API-Key".to_string(), "b".to_string()));

        plugin.on_request_headers(&ctx1);
        plugin.on_request_headers(&ctx1);
        let r1 = plugin.on_request_headers(&ctx1);
        assert!(r1.direct_response.is_some());

        // Key "b" should still be allowed
        let r2 = plugin.on_request_headers(&ctx2);
        assert!(r2.direct_response.is_none());
    }

    // ── PathBlockerPlugin Tests ─────────────────────────────────────────────

    #[test]
    fn test_path_blocker_allows_non_matching() {
        let plugin = PathBlockerPlugin::new("blocker", vec!["/admin".to_string()]);
        let ctx = make_request_ctx(); // path is /api/users
        let result = plugin.on_request_headers(&ctx);
        assert!(result.direct_response.is_none());
    }

    #[test]
    fn test_path_blocker_blocks_matching() {
        let plugin = PathBlockerPlugin::new("blocker", vec!["/api".to_string()]);
        let ctx = make_request_ctx();
        let result = plugin.on_request_headers(&ctx);
        assert!(result.direct_response.is_some());
        assert_eq!(result.direct_response.unwrap().status_code, 403);
    }

    #[test]
    fn test_path_blocker_multiple_patterns() {
        let plugin = PathBlockerPlugin::new(
            "blocker",
            vec!["/admin".to_string(), "/secret".to_string(), "/api".to_string()],
        );
        let ctx = make_request_ctx();
        let result = plugin.on_request_headers(&ctx);
        assert!(result.direct_response.is_some());
    }

    // ── WasmPluginManager Tests ─────────────────────────────────────────────

    #[test]
    fn test_manager_creation() {
        let mgr = WasmPluginManager::new();
        assert_eq!(mgr.plugin_count(), 0);
    }

    #[test]
    fn test_manager_register_plugin() {
        let mgr = WasmPluginManager::new();
        let plugin = Arc::new(HeaderInjectionPlugin::new("test", vec![]));
        let config = WasmPluginConfig {
            name: "test".to_string(),
            phases: vec![WasmPhase::OnRequestHeaders],
            ..Default::default()
        };
        mgr.register(plugin, config);
        assert_eq!(mgr.plugin_count(), 1);
        assert_eq!(mgr.plugin_names(), vec!["test"]);
    }

    #[test]
    fn test_manager_unregister_plugin() {
        let mgr = WasmPluginManager::new();
        let plugin = Arc::new(HeaderInjectionPlugin::new("test", vec![]));
        let config = WasmPluginConfig {
            name: "test".to_string(),
            ..Default::default()
        };
        mgr.register(plugin, config);
        assert!(mgr.unregister("test"));
        assert_eq!(mgr.plugin_count(), 0);
    }

    #[test]
    fn test_manager_unregister_nonexistent() {
        let mgr = WasmPluginManager::new();
        assert!(!mgr.unregister("nonexistent"));
    }

    #[test]
    fn test_manager_priority_ordering() {
        let mgr = WasmPluginManager::new();
        let p1 = Arc::new(HeaderInjectionPlugin::new("low", vec![]));
        let p2 = Arc::new(HeaderInjectionPlugin::new("high", vec![]));
        mgr.register(
            p1,
            WasmPluginConfig { name: "low".into(), priority: 200, ..Default::default() },
        );
        mgr.register(
            p2,
            WasmPluginConfig { name: "high".into(), priority: 10, ..Default::default() },
        );
        let names = mgr.plugin_names();
        assert_eq!(names, vec!["high", "low"]);
    }

    #[test]
    fn test_manager_execute_request_headers() {
        let mgr = WasmPluginManager::new();
        let plugin = Arc::new(HeaderInjectionPlugin::new(
            "injector",
            vec![("X-Plugin".to_string(), "active".to_string())],
        ));
        mgr.register(
            plugin,
            WasmPluginConfig {
                name: "injector".into(),
                phases: vec![WasmPhase::OnRequestHeaders],
                ..Default::default()
            },
        );
        let ctx = make_request_ctx();
        let result = mgr.execute_request_headers(&ctx);
        assert_eq!(result.action, WasmAction::Continue);
        let hdrs = result.headers.unwrap();
        assert_eq!(hdrs.len(), 1);
        assert_eq!(hdrs[0].0, "X-Plugin");
    }

    #[test]
    fn test_manager_execute_short_circuits_on_direct_response() {
        let mgr = WasmPluginManager::new();
        let blocker = Arc::new(PathBlockerPlugin::new("blocker", vec!["/api".to_string()]));
        let injector = Arc::new(HeaderInjectionPlugin::new(
            "injector",
            vec![("X-Should-Not-Appear".to_string(), "true".to_string())],
        ));
        mgr.register(
            blocker,
            WasmPluginConfig {
                name: "blocker".into(),
                priority: 10,
                phases: vec![WasmPhase::OnRequestHeaders],
                ..Default::default()
            },
        );
        mgr.register(
            injector,
            WasmPluginConfig {
                name: "injector".into(),
                priority: 20,
                phases: vec![WasmPhase::OnRequestHeaders],
                ..Default::default()
            },
        );
        let ctx = make_request_ctx();
        let result = mgr.execute_request_headers(&ctx);
        assert!(result.direct_response.is_some());
        assert_eq!(result.direct_response.unwrap().status_code, 403);
    }

    #[test]
    fn test_manager_disabled_plugin_skipped() {
        let mgr = WasmPluginManager::new();
        let plugin = Arc::new(PathBlockerPlugin::new("blocker", vec!["/api".to_string()]));
        mgr.register(
            plugin,
            WasmPluginConfig {
                name: "blocker".into(),
                enabled: false,
                phases: vec![WasmPhase::OnRequestHeaders],
                ..Default::default()
            },
        );
        let ctx = make_request_ctx();
        let result = mgr.execute_request_headers(&ctx);
        assert!(result.direct_response.is_none());
    }

    #[test]
    fn test_manager_wrong_phase_skipped() {
        let mgr = WasmPluginManager::new();
        let plugin = Arc::new(PathBlockerPlugin::new("blocker", vec!["/api".to_string()]));
        mgr.register(
            plugin,
            WasmPluginConfig {
                name: "blocker".into(),
                phases: vec![WasmPhase::OnLog], // not OnRequestHeaders
                ..Default::default()
            },
        );
        let ctx = make_request_ctx();
        let result = mgr.execute_request_headers(&ctx);
        assert!(result.direct_response.is_none());
    }

    #[test]
    fn test_manager_execute_response_headers() {
        let mgr = WasmPluginManager::new();
        // No plugins registered - should return default
        let ctx = make_response_ctx();
        let result = mgr.execute_response_headers(&ctx);
        assert_eq!(result.action, WasmAction::Continue);
    }

    #[test]
    fn test_manager_execute_log() {
        let mgr = WasmPluginManager::new();
        let req = make_request_ctx();
        let resp = make_response_ctx();
        let result = mgr.execute_log(&req, &resp);
        assert_eq!(result.action, WasmAction::Continue);
    }

    #[test]
    fn test_manager_multiple_plugins_merge_headers() {
        let mgr = WasmPluginManager::new();
        let p1 = Arc::new(HeaderInjectionPlugin::new(
            "p1",
            vec![("X-P1".to_string(), "v1".to_string())],
        ));
        let p2 = Arc::new(HeaderInjectionPlugin::new(
            "p2",
            vec![("X-P2".to_string(), "v2".to_string())],
        ));
        mgr.register(
            p1,
            WasmPluginConfig {
                name: "p1".into(),
                priority: 1,
                phases: vec![WasmPhase::OnRequestHeaders],
                ..Default::default()
            },
        );
        mgr.register(
            p2,
            WasmPluginConfig {
                name: "p2".into(),
                priority: 2,
                phases: vec![WasmPhase::OnRequestHeaders],
                ..Default::default()
            },
        );
        let ctx = make_request_ctx();
        let result = mgr.execute_request_headers(&ctx);
        let hdrs = result.headers.unwrap();
        assert_eq!(hdrs.len(), 2);
    }

    #[test]
    fn test_direct_response_serialization() {
        let resp = WasmDirectResponse {
            status_code: 403,
            headers: vec![("X-Reason".to_string(), "blocked".to_string())],
            body: b"Forbidden".to_vec(),
        };
        let json = serde_json::to_string(&resp).unwrap();
        let decoded: WasmDirectResponse = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.status_code, 403);
    }

    #[test]
    fn test_request_context_clone() {
        let ctx = make_request_ctx();
        let cloned = ctx.clone();
        assert_eq!(cloned.method, "GET");
        assert_eq!(cloned.path, "/api/users");
    }

    #[test]
    fn test_response_context_clone() {
        let ctx = make_response_ctx();
        let cloned = ctx.clone();
        assert_eq!(cloned.status_code, 200);
    }
}
